services:
  - type: web
    name: dsalyzer
    env: docker
    plan: free
    autoDeploy: true
    buildCommand: ""
    startCommand: ""
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 7860
